apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigbucket-restrictions-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

