apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beta-restrictions-binding
subjects:
- kind: User
  name: raj
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: beta-namespace-restrictions
  apiGroup: rbac.authorization.k8s.io

